/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActivityCard: typeof import('./src/components/ActivityCard.vue')['default']
    CommonQA: typeof import('./src/components/settings/CommonQA.vue')['default']
    ContactUs: typeof import('./src/components/settings/ContactUs.vue')['default']
    Find: typeof import('./src/components/main/Find.vue')['default']
    FontSize: typeof import('./src/components/settings/FontSize.vue')['default']
    Home: typeof import('./src/components/main/Home.vue')['default']
    Line: typeof import('./src/components/Line.vue')['default']
    Main: typeof import('./src/components/main/Main.vue')['default']
    More: typeof import('./src/components/main/More.vue')['default']
    MyOrder: typeof import('./src/components/order/MyOrder.vue')['default']
    MyPost: typeof import('./src/components/post/MyPost.vue')['default']
    NutCol: typeof import('@nutui/nutui-taro')['Col']
    NutRow: typeof import('@nutui/nutui-taro')['Row']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTabbar: typeof import('@nutui/nutui-taro')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui-taro')['TabbarItem']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    OrderSnap: typeof import('./src/components/order/OrderSnap.vue')['default']
    PostDetail: typeof import('./src/components/post/PostDetail.vue')['default']
    PostSnap: typeof import('./src/components/post/PostSnap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserPosts: typeof import('./src/components/UserPosts.vue')['default']
    UserProfile: typeof import('./src/components/user/UserProfile.vue')['default']
    UserSnap: typeof import('./src/components/user/UserSnap.vue')['default']
  }
}
